"""
SQLAlchemy ORM Models — database/models.py

All database tables are defined here.
Never modify the schema directly — always use Alembic migrations.
Decimals are used for all price and quantity fields — never floats.
All trade records are append-only for audit trail integrity.
"""
from decimal import Decimal
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, String, Numeric, DateTime, Integer,
    UniqueConstraint, Index, create_engine
)
from sqlalchemy.orm import DeclarativeBase, Session


class Base(DeclarativeBase):
    pass


# ── Candles ───────────────────────────────────────────────────────────────────

class CandleModel(Base):
    """
    OHLCV candle data for BTC/USD and ETH/USD.
    Unique constraint on (symbol, timeframe, timestamp) prevents duplicates
    when re-seeding historical data.
    """
    __tablename__ = "candles"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    open = Column(Numeric(precision=20, scale=8), nullable=False)
    high = Column(Numeric(precision=20, scale=8), nullable=False)
    low = Column(Numeric(precision=20, scale=8), nullable=False)
    close = Column(Numeric(precision=20, scale=8), nullable=False)
    volume = Column(Numeric(precision=20, scale=8), nullable=False)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint("symbol", "timeframe", "timestamp", name="uq_candle"),
        Index("ix_candle_symbol_timeframe_timestamp", "symbol", "timeframe", "timestamp"),
    )

    def __repr__(self) -> str:
        return (
            f"<Candle {self.symbol} {self.timeframe} "
            f"{self.timestamp} close={self.close}>"
        )


# ── Signals ───────────────────────────────────────────────────────────────────

class SignalModel(Base):
    """
    Every trade signal generated by the agent pipeline.
    Stored regardless of whether it was approved, rejected, or timed out.
    Append-only — never update or delete signal records.
    """
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)       # long | short
    entry_price = Column(Numeric(precision=20, scale=8), nullable=False)
    stop_loss = Column(Numeric(precision=20, scale=8), nullable=False)
    take_profit = Column(Numeric(precision=20, scale=8), nullable=False)
    position_size = Column(Numeric(precision=20, scale=8), nullable=False)
    risk_amount = Column(Numeric(precision=20, scale=8), nullable=False)
    risk_reward_ratio = Column(Numeric(precision=10, scale=4), nullable=False)
    confidence = Column(Numeric(precision=5, scale=4), nullable=True)
    technical_summary = Column(String(500), nullable=True)
    sentiment_summary = Column(String(500), nullable=True)
    fundamental_summary = Column(String(500), nullable=True)
    coordinator_summary = Column(String(1000), nullable=True)
    status = Column(String(20), nullable=False, default="pending")
    # pending | approved | rejected | timeout | cancelled
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    expires_at = Column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        Index("ix_signal_status_created", "status", "created_at"),
        Index("ix_signal_symbol", "symbol"),
    )

    def __repr__(self) -> str:
        return f"<Signal {self.symbol} {self.direction} {self.status}>"


# ── Trades ────────────────────────────────────────────────────────────────────

class TradeModel(Base):
    """
    Executed trades — paper and live.
    Created when a signal is approved and execution completes.
    Append-only — never update or delete trade records.
    """
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, nullable=False)
    mode = Column(String(10), nullable=False)            # paper | live
    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)       # long | short
    entry_price = Column(Numeric(precision=20, scale=8), nullable=False)
    exit_price = Column(Numeric(precision=20, scale=8), nullable=True)
    position_size = Column(Numeric(precision=20, scale=8), nullable=False)
    stop_loss = Column(Numeric(precision=20, scale=8), nullable=False)
    take_profit = Column(Numeric(precision=20, scale=8), nullable=False)
    pnl = Column(Numeric(precision=20, scale=8), nullable=True)
    pnl_pct = Column(Numeric(precision=10, scale=6), nullable=True)
    status = Column(String(20), nullable=False, default="open")
    # open | closed_tp | closed_sl | closed_manual
    opened_at = Column(DateTime(timezone=True), nullable=False)
    closed_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_trade_mode_status", "mode", "status"),
        Index("ix_trade_symbol_opened", "symbol", "opened_at"),
    )

    def __repr__(self) -> str:
        return f"<Trade {self.symbol} {self.direction} {self.status} pnl={self.pnl}>"


# ── Performance ───────────────────────────────────────────────────────────────

class DailyPerformanceModel(Base):
    """
    Daily P&L snapshot and kill switch events.
    One row per trading day per mode (paper/live).
    """
    __tablename__ = "daily_performance"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(10), nullable=False)            # YYYY-MM-DD
    mode = Column(String(10), nullable=False)            # paper | live
    starting_capital = Column(Numeric(precision=20, scale=8), nullable=False)
    ending_capital = Column(Numeric(precision=20, scale=8), nullable=True)
    daily_pnl = Column(Numeric(precision=20, scale=8), nullable=True)
    daily_pnl_pct = Column(Numeric(precision=10, scale=6), nullable=True)
    total_signals = Column(Integer, default=0)
    approved_signals = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    kill_switch_triggered = Column(Integer, default=0)   # 0 | 1
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint("date", "mode", name="uq_daily_performance"),
        Index("ix_daily_performance_date_mode", "date", "mode"),
    )

    def __repr__(self) -> str:
        return f"<DailyPerformance {self.date} {self.mode} pnl={self.daily_pnl_pct}>"


# ── Reviewer Sessions ─────────────────────────────────────────────────────────

class ReviewerSessionModel(Base):
    """
    Per-decision metadata for the HITL approval gate.
    Records every human decision (approve / cancel / timeout) along with
    timing, override classification, and deviation metrics.
    Append-only — never update or delete rows.
    """
    __tablename__ = "reviewer_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, nullable=False)           # references signals.id
    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)        # long | short
    confidence = Column(Numeric(precision=6, scale=4), nullable=False)
    recommended_size = Column(Numeric(precision=20, scale=8), nullable=False)
    sent_at = Column(DateTime(timezone=True), nullable=False)
    decided_at = Column(DateTime(timezone=True), nullable=True)
    decision = Column(String(10), nullable=False)         # approve | cancel | timeout
    decision_latency_seconds = Column(Numeric(precision=8, scale=3), nullable=True)
    hour_of_day = Column(Integer, nullable=False)         # 0–23 UTC
    is_override = Column(Boolean, nullable=False, default=False)
    # Snapshot metrics at decision time:
    historical_override_rate = Column(Numeric(precision=5, scale=4), nullable=True)
    deviation_z_score = Column(Numeric(precision=6, scale=3), nullable=True)
    escalation_flag = Column(Boolean, nullable=False, default=False)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_reviewer_sessions_decided_at", "decided_at"),
        Index("ix_reviewer_sessions_signal_id", "signal_id"),
    )

    def __repr__(self) -> str:
        return f"<ReviewerSession signal={self.signal_id} decision={self.decision}>"


# ── Discretionary Signals ─────────────────────────────────────────────────────

class DiscretionarySignalModel(Base):
    """
    Human-sourced directional trade ideas submitted by the portfolio manager.
    Fed into the meta-labeling layer (Phase 3) as additional features.
    provenance is always 'human' — distinguishes from model-sourced inputs.
    """
    __tablename__ = "discretionary_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_ref = Column(String(36), nullable=False, unique=True)  # UUID string
    symbol = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)        # long | short
    conviction = Column(Numeric(precision=4, scale=3), nullable=False)
    provenance = Column(String(10), nullable=False, default="human")
    submitted_at = Column(DateTime(timezone=True), nullable=False)
    meta_label_consumed = Column(Boolean, nullable=False, default=False)
    consumed_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_discretionary_signals_consumed", "meta_label_consumed"),
    )

    def __repr__(self) -> str:
        return (
            f"<DiscretionarySignal {self.symbol} {self.direction} "
            f"conviction={self.conviction} consumed={self.meta_label_consumed}>"
        )