"""initial schema

Revision ID: 9f7cc2db4f7c
Revises: 
Create Date: 2026-04-11 22:06:47.713060
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f7cc2db4f7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle')
    )
    op.create_index('ix_candle_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('daily_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ending_capital', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('approved_signals', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('kill_switch_triggered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'mode', name='uq_daily_performance')
    )
    op.create_index('ix_daily_performance_date_mode', 'daily_performance', ['date', 'mode'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('technical_summary', sa.String(length=500), nullable=True),
    sa.Column('sentiment_summary', sa.String(length=500), nullable=True),
    sa.Column('fundamental_summary', sa.String(length=500), nullable=True),
    sa.Column('coordinator_summary', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_status_created', 'signals', ['status', 'created_at'], unique=False)
    op.create_index('ix_signal_symbol', 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_mode_status', 'trades', ['mode', 'status'], unique=False)
    op.create_index('ix_trade_symbol_opened', 'trades', ['symbol', 'opened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_symbol_opened', table_name='trades')
    op.drop_index('ix_trade_mode_status', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signal_symbol', table_name='signals')
    op.drop_index('ix_signal_status_created', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_daily_performance_date_mode', table_name='daily_performance')
    op.drop_table('daily_performance')
    op.drop_index('ix_candle_symbol_timeframe_timestamp', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
